#!/usr/bin/env bash
# Start Apache and create an HTML file to return "Hello Holberton"

# Create the HTML file in the Apache root directory
echo "Hello Holberton" > /var/www/html/index.html

# Start the Apache service
service apache2 start

