#!/usr/bin/env bash

# Customizing a 404-error_page and configuring web servers

# Updating packages before performing installations
echo -e "Updating packages...\n"
sudo apt-get update -y -qq

# Function to install packages if not already installed
function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get install -y "$1" -qq
    else
        echo -e "$1 is already installed.\n"
    fi
}

# Install nginx
install nginx

# Allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Creating new index
echo "Hello World!" > /var/www/html/index.html

# Create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/nginx-sites-enabled_default.backup

# Nginx configuration
server_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    
    location / {
        try_files \$uri \$uri/ =404;
    }
    
    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://www.youtube.com/watch?v=rpaonSDPw7Y permanent;
    }
    
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
"

# Write the configuration to the Nginx config file
echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart nginx after implementing changes
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi

echo -e "Configured Nginx with custom settings.\n"

