#!/usr/bin/env bash
# Configures nginx to run and listen on port 80

# Update the Nginx configuration file to listen on port 80
sed -i "s/listen 8080 default_server;/listen 80 default_server;/g" /etc/nginx/sites-available/default

# Ensure the PID file is removed if it exists
rm -f /run/nginx.pid

# Restart the Nginx service to apply changes
service nginx restart

